import os
from flask import Flask, request, jsonify
import uuid
import re
import math
from datetime import datetime
from groq import Groq
from dotenv import load_dotenv
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

load_dotenv()
app = Flask(__name__)

# Initialize Rate Limiter
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
audit_log_db = []

def analyze_stylometrics(text):
    """
    Signal 1: Analyzes sentence length variance.
    Returns a confidence score between 0.0 (High Human) and 1.0 (High AI).
    """
    # Split the text into sentences based on punctuation
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    
    # Fallback if text is too short or lacks punctuation
    if len(sentences) < 2:
        return 0.50 
    
    # Count the words in each sentence
    word_counts = [len(s.split()) for s in sentences]
    
    # Calculate the mean (average) sentence length
    mean_length = sum(word_counts) / len(word_counts)
    
    # Calculate the variance and standard deviation
    variance = sum((x - mean_length) ** 2 for x in word_counts) / len(word_counts)
    std_dev = math.sqrt(variance)
    
    # Calibrate to a 0.0 - 1.0 score:
    # Uniform text (std_dev ~ 2 words) -> AI (1.0)
    # Varied text (std_dev ~ 10 words) -> Human (0.0)
    raw_score = 1.0 - ((std_dev - 2) / 8)
    
    # Clamp the final score strictly between 0.0 and 1.0
    final_score = max(0.0, min(1.0, raw_score))
    return round(final_score, 2)


def analyze_semantics_llm(text):
    """
    Signal 2: Semantic analysis using Groq's Llama 3.3.
    Returns a confidence score between 0.0 (High Human) and 1.0 (High AI).
    """
    prompt = f"""
    Analyze the following text and determine if it was written by a human or generated by an AI.
    Focus on semantic coherence, tonal shifts, and predictability.
    Respond ONLY with a single decimal number between 0.0 (highly likely human) and 1.0 (highly likely AI).
    Do not include any other text, words, or formatting.
    
    Text: "{text}"
    """
    try:
        response = groq_client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model="llama-3.3-70b-versatile",
            temperature=0.0 # Keep it deterministic
        )
        # Extract the raw text and convert it to a float
        score_text = response.choices[0].message.content.strip()
        score = float(score_text)
        
        # Clamp strictly between 0.0 and 1.0 just in case the LLM hallucinates
        return max(0.0, min(1.0, score))
    except Exception as e:
        print(f"Groq API Error: {e}")
        return 0.50 # Fallback to uncertain if the API fails



@app.route('/submit', methods=['POST'])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    text = data.get('text', '')
    creator_id = data.get('creator_id', 'unknown')
    
    content_id = str(uuid.uuid4())
    stylometric_score = analyze_stylometrics(text)
    
    llm_score = None
    
    if stylometric_score < 0.25:
        final_confidence_score = stylometric_score
        reasoning = f"Fast-tracked human. Stylometric score ({stylometric_score}) safely below 0.25 threshold."
    else:
        llm_score = analyze_semantics_llm(text)
        final_confidence_score = round((stylometric_score + llm_score) / 2, 2)
        reasoning = f"Scores averaged. Stylometric: {stylometric_score} | LLM: {llm_score}"
        
    # Apply the exact Transparency Label design from your spec
    if final_confidence_score <= 0.24:
        label = "Analysis indicates this content was highly likely written by a human."
    elif 0.25 <= final_confidence_score <= 0.74:
        label = "Analysis shows mixed signals. The origin of this content is uncertain."
    else:
        label = "Analysis indicates this content was highly likely generated by AI."
    
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "stylometric_score": stylometric_score,
        "llm_score": llm_score,
        "final_confidence_score": final_confidence_score,
        "label": label,
        "status": "classified",
        "appeal_reasoning": None
    }
    audit_log_db.append(log_entry)
    
    return jsonify({
        "content_id": content_id,
        "confidence_score": final_confidence_score,
        "label": label,
        "reasoning": reasoning
    }), 200



@app.route('/log', methods=['GET'])
def get_log():
    # A simple route so you can view your audit log in the browser
    return jsonify({"entries": audit_log_db}), 200


@app.route('/appeal', methods=['POST'])
@limiter.limit("5 per minute")
def appeal():
    data = request.get_json()
    content_id = data.get('content_id')
    creator_reasoning = data.get('creator_reasoning')
    
    if not content_id or not creator_reasoning:
        return jsonify({"error": "Missing content_id or creator_reasoning"}), 400
        
    # Find the matching entry in our audit log
    for entry in audit_log_db:
        if entry['content_id'] == content_id:
            entry['status'] = 'under_review'
            entry['appeal_reasoning'] = creator_reasoning
            return jsonify({"message": f"Appeal received for {content_id}. Status updated to under_review."}), 200
            
    return jsonify({"error": "Content ID not found."}), 404


if __name__ == '__main__':
    app.run(debug=True, port=5001)

